export const TEST_ACTIONONE = 'TEST_ACTIONONE';
export const TEST_ACTIONTWO = 'TEST_ACTIONTWO';
export const TEST_FETCHTEXTREQUEST = 'TEST_FETCHTEXTREQUEST';
export const TEST_FETCHTEXTSUCCESS = 'TEST_FETCHTEXTSUCCESS';